### PR TITLE
Fix: testing array range before retrieving an element

### PR DESCRIPTION
**Pull request by jibeex**

### CODE REVIEW

**Comment by jibeex** [comment]
Hi, I am not available to do that change for the moment. But I may do that later when I have got some spare time.

**Comment by chili-ios** [comment]
@jibeex no problem. I will merge when it's complete.

**Comment by jibeex** [comment]
It will be in another PR, so that we can keep PR small and focus.

**Comment by chili-ios** [comment]
@jibeex , It's the same logic, so it should be in one PR :)

**Pull request closed without merging**
