### PR TITLE
Migrating project to swift 4

### PR DESCRIPTION
**Pull request by fpinvidio**
Exposed updateFrame function to objc as required for swift-4.
Updated project settings.

### CODE REVIEW

**Comment by chili-ios** [comment]
hi @fpinvidio ,

Do we need flag SWIFT_SWIFT3_OBJC_INFERENCE to be `on`? Just checked with xCode 9 beta 4, and everything works with `default` value.

**Comment by fpinvidio** [comment]
Actually it should be set to default or off. But before changing it, it would be wise to run the project with the env variable SWIFT_DEBUG_IMPLICIT_OBJC_ENTRYPOINT for identifying any remaining functions that need @objc.

https://stackoverflow.com/questions/44379348/the-use-of-swift-3-objc-inference-in-swift-4-mode-is-deprecated

**Comment by Felizolinha** [comment]
It makes a lot of sense to use this flag, as it reduces the file size of the project's binary.

**Comment by agordeev** [comment]
Are you going to merge this PR? Nice lib btw ;)

**Pull request merged**
