### PR TITLE
Added support to Multiple Tint Colors

### PR DESCRIPTION
**Pull request by nunoonun**
I was in need of adding tint colors to different pages, everything works the same way (by using the `tintColor` property) unless you edit the `tintColors` array or `insertTintColor(color:position:)`

Every subclass was updated to support this new feature, they also blend colours when switching places. The active tint color is always the selected (it doesn't change)

### CODE REVIEW

**Comment by mihailstumkins** [comment]
Hey, this looks great! 
If you could add an example to example project I'd say LGTM!

**Comment by nunoonun** [comment]
Hey! I've pushed the changes to the Example project. I hope this comes handy to anyone

**Comment by chili-ios** [comment]
@nunoonun , will you merge?

**Comment by nunoonun** [comment]
@chili-ios I can't merge it. I don't have any write access. It need to be you doing it

**Pull request merged**
